INSERT OR REPLACE INTO config (key, value) VALUES
  ('store_name', 'MODA FEMENINA'),
  ('store_tagline', 'Moda femenina con estilo y elegancia'),
  ('store_story', 'MODA FEMENINA nació con la idea de vestir a la mujer moderna que busca sentirse segura y elegante en cada ocasión. Seleccionamos cada prenda pensando en la calidad, el corte y el detalle, para que encuentres en nuestro catálogo esas piezas que marcan la diferencia.'),
  ('store_mission', 'Ofrecer moda femenina de calidad con diseños actuales, atención personalizada y una experiencia de compra cálida y cercana. Queremos que cada mujer encuentre en MODA FEMENINA su estilo propio.'),
  ('store_hours', 'Lun – Sáb: 10:00 – 20:00'),
  ('store_address', 'Yacuiba, Bolivia'),
  ('store_email', 'hola@modafemenina.bo'),
  ('store_instagram', '@moda.femenina.bo');

INSERT OR REPLACE INTO categories (id, name, image, sort) VALUES
  ('camisas', 'Camisas', 'https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?w=600', 1),
  ('sacos', 'Sacos', 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=600', 2),
  ('pantalones', 'Pantalones de Vestir', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600', 3),
  ('bleizer', 'Bléizer', 'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=600', 4),
  ('vestidos', 'Vestidos de Fiesta', 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600', 5),
  ('accesorios', 'Accesorios', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600', 6);

INSERT INTO promotions (badge, title, sub, image, cat, full_description, valid_until, conditions) VALUES
  ('NUEVA COLECCIÓN', 'Bléizer y Sacos', 'Elegancia atemporal', 'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=1200', 'bleizer', 'Nueva colección de bléizers y sacos en telas premium, con cortes entallados y detalles que marcan la diferencia. Perfectos para el trabajo, eventos o el día a día.', 'Consultar disponibilidad en tienda', '["Precio final según modelo", "Envío coordinado por WhatsApp", "Sujeto a stock disponible"]'),
  ('BÁSICOS', 'Camisas Esenciales', 'El básico que nunca falla', 'https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?w=1200', 'camisas', 'Camisas femeninas en algodón y mezclas premium, disponibles en tonos neutros y colores de temporada. Ideales para combinar en cualquier look.', 'Consultar disponibilidad', '["Talles del S al XL", "Colores según stock", "Cambio dentro de 7 días"]'),
  ('OFERTA', 'Pantalones de Vestir', 'Comodidad y estilo', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=1200', 'pantalones', 'Pantalones de vestir femeninos con cortes modernos y telas con elastano para mayor comodidad. Disponibles en negro, gris, beige y azul marino.', 'Consultar disponibilidad', '["Talles del 36 al 46", "Varios colores disponibles", "Sujeto a stock"]');

INSERT INTO projects (id, title, cat, location, client, duration, image, description, images_json) VALUES
  (1, 'Look Ejecutivo Femenino', 'sacos', 'Colección actual', 'Disponible', 'Entrega en 24-48 h', 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=900', 'Conjunto de saco entallado + pantalón de vestir + camisa blanca. Un look clásico y sofisticado para la oficina o eventos formales.', '["https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=1100","https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=1100"]'),
  (2, 'Bléizer Oversize', 'bleizer', 'Colección actual', 'Disponible', 'Entrega en 24-48 h', 'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=900', 'Bléizer oversize en tono lila empolvado, ideal para looks casuales y elegantes. Combínalo con jeans o pantalones de vestir.', '["https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=1100"]'),
  (3, 'Camisa de Seda', 'camisas', 'Colección actual', 'Disponible', 'Entrega en 24-48 h', 'https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?w=900', 'Camisa de seda con caída fluida y botones nacarados. Un básico de lujo que realza cualquier look, del trabajo a la noche.', '["https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?w=1100"]'),
  (4, 'Pantalón de Vestir Tiro Alto', 'pantalones', 'Colección actual', 'Disponible', 'Entrega en 24-48 h', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=900', 'Pantalón de vestir de tiro alto con pinza frontal, corte recto y tela con elastano. Estiliza la figura y es cómodo para todo el día.', '["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=1100"]'),
  (5, 'Vestido de Fiesta Elegante', 'vestidos', 'Colección actual', 'Disponible', 'Entrega en 24-48 h', 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900', 'Vestido de fiesta en tono rosado con detalles bordados, escote elegante y caída fluida. La pieza perfecta para una ocasión especial.', '["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=1100"]'),
  (6, 'Accesorios de Temporada', 'accesorios', 'Colección actual', 'Disponible', 'Entrega en 24-48 h', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900', 'Carteras, pañuelos, cinturones y collares seleccionados para complementar tu look con un toque sofisticado.', '["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=1100"]');

INSERT INTO products (id, sku, name, brand, price, cat, img, images_json, desc, description, details_json, colors_json, sizes_json, pairs_with_json) VALUES
  (1, 'LR-CAM-001', 'Camisa de Seda', 'MODA FEMENINA', 320, 'camisas', 'https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?w=900', '["https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?w=900","https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=900"]', 'Camisa de seda con caída fluida y botones nacarados.', '<p>Camisa de <strong>seda natural</strong> con caída fluida, cuello clásico y botones nacarados. Su textura suave y luminosa realza cualquier look.</p><p>Ideal para el trabajo, eventos o para elevar un outfit casual. Disponible en tonos neutros y de temporada.</p>', '{"Material":"Seda natural","Cuello":"Clásico","Cierre":"Botones nacarados","Cuidado":"Lavado a mano"}', '[{"hex":"#f4d9e4","name":"Rosa empolvado"},{"hex":"#ffffff","name":"Blanco"},{"hex":"#1e1a24","name":"Negro"}]', '["XS","S","M","L","XL"]', '[3,5]'),
  (2, 'LR-SAC-002', 'Saco Entallado', 'MODA FEMENINA', 580, 'sacos', 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=900', '["https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=900"]', 'Saco entallado de corte clásico, elegante y versátil.', '<p>Saco entallado de <strong>corte clásico</strong> con hombros estructurados y botonadura simple. Perfecto para el trabajo o eventos formales.</p><p>Confeccionado en mezcla de lana con forro interior satinado. Disponible en tonos neutros y de moda.</p>', '{"Material":"Mezcla de lana","Corte":"Entallado","Forro":"Satín","Cuidado":"Lavado en seco"}', '[{"hex":"#6b4c9a","name":"Violeta"},{"hex":"#1e1a24","name":"Negro"},{"hex":"#8b7355","name":"Beige"}]', '["XS","S","M","L","XL"]', '[3,5]'),
  (3, 'LR-PAN-003', 'Pantalón de Vestir Tiro Alto', 'MODA FEMENINA', 380, 'pantalones', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=900', '["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=900"]', 'Pantalón de vestir de tiro alto con pinza frontal.', '<p>Pantalón de vestir de <strong>tiro alto</strong> con pinza frontal y corte recto. Estiliza la figura y alarga la silueta.</p><p>Confeccionado en tela con elastano para mayor comodidad. Ideal para el trabajo y ocasiones formales.</p>', '{"Material":"Poliéster con elastano","Corte":"Recto tiro alto","Cierre":"Cremallera invisible","Cuidado":"Lavado a máquina"}', '[{"hex":"#1e1a24","name":"Negro"},{"hex":"#8b7355","name":"Beige"},{"hex":"#3a4a6b","name":"Azul marino"}]', '["36","38","40","42","44","46"]', '[1,2]'),
  (4, 'LR-BLZ-004', 'Bléizer Oversize', 'MODA FEMENINA', 460, 'bleizer', 'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=900', '["https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=900"]', 'Bléizer oversize de corte moderno, casual y elegante.', '<p>Bléizer <strong>oversize</strong> de corte moderno y relajado. Hombros caídos y largo a la cadera para un look actual y elegante.</p><p>Perfecto para combinar con jeans, pantalones de vestir o vestidos. Disponible en tonos suaves y de moda.</p>', '{"Material":"Mezcla de poliéster","Corte":"Oversize","Forro":"Sí","Cuidado":"Lavado en seco"}', '[{"hex":"#6b4c9a","name":"Violeta"},{"hex":"#e8b4c8","name":"Rosa suave"},{"hex":"#1e1a24","name":"Negro"}]', '["S","M","L","XL"]', '[3,5]'),
  (5, 'LR-VES-005', 'Vestido de Fiesta Elegante', 'MODA FEMENINA', 620, 'vestidos', 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900', '["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900"]', 'Vestido de fiesta en tono rosado con detalles bordados.', '<p>Vestido de fiesta con <strong>detalles bordados</strong> en tono rosado. Escote elegante, corte en la cintura y caída fluida hasta la rodilla.</p><p>La pieza perfecta para una ocasión especial. Combínalo con tacos y accesorios dorados.</p>', '{"Material":"Gasa con bordados","Corte":"Entallado en cintura","Largo":"Midi","Cuidado":"Lavado a mano"}', '[{"hex":"#e8b4c8","name":"Rosa"},{"hex":"#6b4c9a","name":"Violeta"},{"hex":"#1e1a24","name":"Negro"}]', '["XS","S","M","L"]', '[6,1]'),
  (6, 'LR-ACC-006', 'Set de Accesorios Femeninos', 'MODA FEMENINA', 180, 'accesorios', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900', '["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900"]', 'Set de cartera, pañuelo y collar dorado.', '<p>Set de <strong>accesorios femeninos</strong>: cartera de mano, pañuelo de seda y collar dorado. El toque final de cualquier look.</p><p>Ideal para regalar o darte un gustito. Disponible en tonos rosados, violetas y neutros.</p>', '{"Incluye":"Cartera + pañuelo + collar","Material":"Cuero sintético y metal","Estilo":"Elegante casual","Cuidado":"Limpiar con paño"}', '[{"hex":"#e8b4c8","name":"Rosa"},{"hex":"#6b4c9a","name":"Violeta"},{"hex":"#1e1a24","name":"Negro"}]', '["Único"]', '[5,1,2]');
