name = "moda-femenina"
compatibility_date = "2025-10-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "moda-femenina-db"
database_id = "d27dc1ff-b2c9-4260-9595-26f4fb8cfdad"

[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "moda-femenina-assets"